name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 开始打包 执行npm install
      run: |
        npm install
      env:
        CI: true
    - name: 执行npm run build:h5
      run: |
        npm run build:h5
    - name: 查看当前文件夹下的文件
      run: |
        ls
    - name: 进入dist文件夹并查看文件
      run: |
        cd dist/
        ls
    - name: git初始化
      run: |
        git --help
        git init
    - name: 查看git远程地址
      run: |
        git remote -v
        # git remote add origin https://github.com/cathe-zhang/github_action_test.git
    - name: 设置git用户信息
      run: |
        git config --global user.name cathe-zhang
        git config --global user.email zhangle_media@hotmail.com
    - name: git add .
      run: |
        git add .
    - name: git commit -m 'deploy'
      run: |
        git commit -m 'deploy'
    - name: 拉取代码
      run: |
        git pull origin gh-pages
    - name: 推送代码 git push -f origin gh-pages
      run: |

        git push -f origin gh-pages
